[versions]
agp = "8.13.1"
androidx-activity = "1.12.0"
androidx-lifecycle = "2.9.6"
androidx-navigation = "2.9.1"
androidx-room = "2.8.4"
androidx-sqliteBundled = "2.6.2"
androidx-work = "2.11.0"
appdirs = "1.5.0"
axion-release = "1.21.0"

caupain = "1.6.1"
compose-hotReload = "1.0.0-rc04"
compose-multiplatform = "1.9.3"

detekt = "1.23.8"
detekt-compose = "0.4.28"

kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
ksp = "2.3.3"

metro = "0.7.7"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidx-sqliteBundled" }
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
appdirs = { module = "net.harawata:appdirs", version.ref = "appdirs" }

detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-compose" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }
axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release" }

caupain = { id = "com.deezer.caupain", version.ref = "caupain" }
compose-hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hotReload" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
